export type Player = {
  id: string;
  nickname: string;
  realName: string;
  country: string;
  teamId: string;
  team: string;
  role: "AWPer" | "Rifler" | "IGL" | "Support" | "Стример";
  verified: boolean;
  bio?: string;
  twitch?: string;      // ссылка на Twitch-канал
  updated: string;      // дата последнего обновления настроек

  dpi: number;
  sens: number;
  edpi: number;
  hz: number;

  resolution: string;
  aspect: string;

  mouse: string;
  mousepad: string;
  keyboard: string;
  monitor: string;
  headset: string;

  crosshairCode: string;
  launchOptions: string[];
  viewmodel: string;    // готовые консольные команды
  binds: { key: string; action: string }[];
};

export const players: Player[] = [
  // ============ TEAM SPIRIT ============
  {
    id: "donk", nickname: "donk", realName: "Данил Крышковец", country: "🇷🇺",
    teamId: "spirit", team: "Team Spirit", role: "Rifler", verified: true,
    bio: "Лучший rifler 2024 года. Молодой, дерзкий, агрессивный.",
    updated: "2026-09-15",
    dpi: 800, sens: 1.25, edpi: 1000, hz: 4000,
    resolution: "1280×960", aspect: "4:3 Stretched",
    mouse: "Logitech G Pro X Superlight 2", mousepad: "Artisan Zero XL Soft",
    keyboard: "Logitech G Pro X TKL", monitor: "Zowie XL2566K", headset: "HyperX Cloud II",
    crosshairCode: "CSGO-2w3SK-HasGr-BYazP-JL2Sv-o8veM",
    launchOptions: ["-novid", "-console", "-freq 360", "-tickrate 128", "+fps_max 0"],
    viewmodel: "viewmodel_fov 68; viewmodel_offset_x 2.5; viewmodel_offset_y 0; viewmodel_offset_z -1.5; viewmodel_presetpos 1;",
    binds: [{ key: "MOUSE4", action: "C4" }, { key: "MOUSE5", action: "Flashbang" }, { key: "Q", action: "Switch last weapon" }, { key: "V", action: "Smoke" }],
  },
  {
    id: "sh1ro", nickname: "sh1ro", realName: "Дмитрий Соколов", country: "🇷🇺",
    teamId: "spirit", team: "Team Spirit", role: "AWPer", verified: true,
    bio: "Один из лучших снайперов СНГ-сцены.",
    updated: "2026-09-15",
    dpi: 400, sens: 1.5, edpi: 600, hz: 1000,
    resolution: "1280×960", aspect: "4:3 Stretched",
    mouse: "Logitech G Pro X Superlight", mousepad: "Logitech G640",
    keyboard: "Logitech G Pro X", monitor: "Zowie XL2566K", headset: "HyperX Cloud II",
    crosshairCode: "—",
    launchOptions: ["-novid", "-console", "+fps_max 0"],
    viewmodel: "viewmodel_fov 68; viewmodel_offset_x 2.5; viewmodel_offset_y 0; viewmodel_offset_z -1.5; viewmodel_presetpos 1;",
    binds: [],
  },
  {
    id: "chopper", nickname: "chopper", realName: "Леонид Вишняков", country: "🇷🇺",
    teamId: "spirit", team: "Team Spirit", role: "IGL", verified: true,
    bio: "Капитан Team Spirit. Опытный IGL.",
    updated: "2026-09-15",
    dpi: 400, sens: 1.4, edpi: 560, hz: 1000,
    resolution: "1024×768", aspect: "4:3 Black Bars",
    mouse: "VAXEE NP-01S Pink", mousepad: "Logitech G640",
    keyboard: "Logitech G Pro X", monitor: "Zowie XL2546K", headset: "HyperX Cloud II",
    crosshairCode: "CSGO-OGr5a-GBAXm-dcE2Q-WYJbP-76nQD",
    launchOptions: [],
    viewmodel: "viewmodel_fov 68; viewmodel_offset_x 2.3; viewmodel_offset_y 2; viewmodel_offset_z -2; viewmodel_presetpos 3;",
    binds: [],
  },
  {
    id: "magixx", nickname: "magixx", realName: "Борис Воробьёв", country: "🇷🇺",
    teamId: "spirit", team: "Team Spirit", role: "Rifler", verified: true,
    bio: "Молодой рифлер Team Spirit.",
    updated: "2026-09-15",
    dpi: 400, sens: 1.9, edpi: 760, hz: 1000,
    resolution: "1280×960", aspect: "4:3 Stretched",
    mouse: "Logitech G Pro X Superlight", mousepad: "Logitech G640",
    keyboard: "Logitech G Pro X", monitor: "Zowie XL2546K", headset: "HyperX Cloud II",
    crosshairCode: "—",
    launchOptions: ["-novid", "-console"],
    viewmodel: "viewmodel_fov 68; viewmodel_offset_x 2.5; viewmodel_offset_y 0; viewmodel_offset_z -1.5; viewmodel_presetpos 1;",
    binds: [],
  },
  {
    id: "zont1x", nickname: "zont1x", realName: "Мирослав Плахотя", country: "🇷🇺",
    teamId: "spirit", team: "Team Spirit", role: "Rifler", verified: true,
    bio: "Молодой рифлер Team Spirit.",
    updated: "2026-09-15",
    dpi: 400, sens: 1.6, edpi: 640, hz: 1000,
    resolution: "1280×960", aspect: "4:3 Stretched",
    mouse: "Logitech G Pro X Superlight 2", mousepad: "Logitech G640",
    keyboard: "Logitech G Pro X", monitor: "Zowie XL2566K", headset: "HyperX Cloud II",
    crosshairCode: "—",
    launchOptions: ["-novid", "-console", "-freq 360"],
    viewmodel: "viewmodel_fov 68; viewmodel_offset_x 2.5; viewmodel_offset_y 0; viewmodel_offset_z -1.5; viewmodel_presetpos 1;",
    binds: [],
  },

  // ============ NAVI ============
  {
    id: "s1mple", nickname: "s1mple", realName: "Александр Костылев", country: "🇺🇦",
    teamId: "navi", team: "Natus Vincere", role: "AWPer", verified: true,
    bio: "Легенда CS. Самый титулованный игрок в истории.",
    updated: "2026-09-15",
    dpi: 400, sens: 3.09, edpi: 1236, hz: 4000,
    resolution: "1280×960", aspect: "4:3 Stretched",
    mouse: "Zowie EC2-CW", mousepad: "Logitech G640",
    keyboard: "Logitech G Pro X", monitor: "Zowie XL2566K", headset: "HyperX Cloud II",
    crosshairCode: "CSGO-uCiX4-K9rbx-MVbTM-n3wDU-Gjj5P",
    launchOptions: ["-novid", "-console", "-freq 360", "+fps_max 0"],
    viewmodel: "viewmodel_fov 68; viewmodel_offset_x 2.5; viewmodel_offset_y 0; viewmodel_offset_z -1.5; viewmodel_presetpos 1;",
    binds: [{ key: "Q", action: "Switch last weapon" }, { key: "MOUSE4", action: "C4" }],
  },
  {
    id: "b1t", nickname: "b1t", realName: "Валерий Ваховский", country: "🇺🇦",
    teamId: "navi", team: "Natus Vincere", role: "Rifler", verified: true,
    bio: "Молодой рифлер NAVI.",
    updated: "2026-09-15",
    dpi: 400, sens: 1.65, edpi: 660, hz: 1000,
    resolution: "1280×960", aspect: "4:3 Stretched",
    mouse: "Logitech G Pro X Superlight", mousepad: "Logitech G640",
    keyboard: "Logitech G Pro X", monitor: "Zowie XL2546K", headset: "HyperX Cloud II",
    crosshairCode: "—",
    launchOptions: ["-novid", "-console"],
    viewmodel: "viewmodel_fov 68; viewmodel_offset_x 2.5; viewmodel_offset_y 0; viewmodel_offset_z -1.5; viewmodel_presetpos 1;",
    binds: [],
  },
  {
    id: "w0nderful", nickname: "w0nderful", realName: "Игорь Жданов", country: "🇺🇦",
    teamId: "navi", team: "Natus Vincere", role: "AWPer", verified: true,
    bio: "Молодой снайпер NAVI.",
    updated: "2026-09-15",
    dpi: 400, sens: 1.9, edpi: 760, hz: 1000,
    resolution: "1280×960", aspect: "4:3 Stretched",
    mouse: "Logitech G Pro X Superlight", mousepad: "Logitech G640",
    keyboard: "Logitech G Pro X", monitor: "Zowie XL2566K", headset: "HyperX Cloud II",
    crosshairCode: "—",
    launchOptions: ["-novid", "-console"],
    viewmodel: "viewmodel_fov 68; viewmodel_offset_x 2.5; viewmodel_offset_y 0; viewmodel_offset_z -1.5; viewmodel_presetpos 1;",
    binds: [],
  },
  {
    id: "aleksib", nickname: "Aleksib", realName: "Алекси Виролайнен", country: "🇫🇮",
    teamId: "navi", team: "Natus Vincere", role: "IGL", verified: true,
    bio: "Капитан NAVI. Один из лучших IGL современности.",
    updated: "2026-09-15",
    dpi: 800, sens: 1.2, edpi: 960, hz: 1000,
    resolution: "1280×960", aspect: "4:3 Stretched",
    mouse: "Logitech G Pro X Superlight", mousepad: "Logitech G640",
    keyboard: "Logitech G Pro X", monitor: "Zowie XL2546K", headset: "HyperX Cloud II",
    crosshairCode: "—",
    launchOptions: ["-novid", "-console"],
    viewmodel: "viewmodel_fov 68; viewmodel_offset_x 2.5; viewmodel_offset_y 0; viewmodel_offset_z -1.5; viewmodel_presetpos 1;",
    binds: [],
  },

  // ============ G2 ============
  {
    id: "m0nesy", nickname: "m0NESY", realName: "Илья Осипов", country: "🇷🇺",
    teamId: "g2", team: "G2 Esports", role: "AWPer", verified: true,
    bio: "Один из лучших AWP-игроков мира.",
    updated: "2026-09-15",
    dpi: 400, sens: 2.0, edpi: 800, hz: 4000,
    resolution: "1280×960", aspect: "4:3 Stretched",
    mouse: "Logitech G Pro X Superlight 2", mousepad: "Logitech G640",
    keyboard: "Logitech G Pro X TKL", monitor: "Zowie XL2566K", headset: "Logitech G Pro X",
    crosshairCode: "CSGO-ODtx8-wadQE-6iaxz-YPZA2-KS8SA",
    launchOptions: ["-novid", "-console", "-freq 360", "+fps_max 0"],
    viewmodel: "viewmodel_fov 68; viewmodel_offset_x 2.5; viewmodel_offset_y 0; viewmodel_offset_z -1.5; viewmodel_presetpos 1;",
    binds: [{ key: "Q", action: "Switch last weapon" }],
  },
  {
    id: "niko", nickname: "NiKo", realName: "Никола Ковач", country: "🇧🇦",
    teamId: "g2", team: "G2 Esports", role: "Rifler", verified: true,
    bio: "Один из лучших рифлеров мира. Легенда сцены.",
    updated: "2026-09-15",
    dpi: 400, sens: 1.55, edpi: 620, hz: 1000,
    resolution: "1280×960", aspect: "4:3 Stretched",
    mouse: "Logitech G Pro X Superlight 2", mousepad: "Logitech G640",
    keyboard: "Logitech G Pro X", monitor: "Zowie XL2566K", headset: "Logitech G Pro X",
    crosshairCode: "—",
    launchOptions: ["-novid", "-console"],
    viewmodel: "viewmodel_fov 68; viewmodel_offset_x 2.5; viewmodel_offset_y 0; viewmodel_offset_z -1.5; viewmodel_presetpos 1;",
    binds: [],
  },
  {
    id: "hunter", nickname: "huNter-", realName: "Неманья Ковач", country: "🇧🇦",
    teamId: "g2", team: "G2 Esports", role: "Rifler", verified: true,
    bio: "Двоюродный брат NiKo. Стабильный рифлер G2.",
    updated: "2026-09-15",
    dpi: 800, sens: 1.25, edpi: 1000, hz: 1000,
    resolution: "1350×1080", aspect: "5:4 Stretched",
    mouse: "Logitech G Pro X Superlight", mousepad: "Logitech G640",
    keyboard: "Logitech G Pro X", monitor: "Zowie XL2546K", headset: "Logitech G Pro X",
    crosshairCode: "CSGO-3q4Gs-VYeEJ-5hb2i-MDbqB-uvwPB",
    launchOptions: ["-novid", "-console"],
    viewmodel: "viewmodel_fov 68; viewmodel_offset_x 2.5; viewmodel_offset_y 0; viewmodel_offset_z -1.5; viewmodel_presetpos 1;",
    binds: [],
  },

  // ============ VIRTUS.PRO ============
  {
    id: "jame", nickname: "Jame", realName: "Джами Али", country: "🇷🇺",
    teamId: "vp", team: "Virtus.pro", role: "AWPer", verified: true,
    bio: "Снайпер и капитан Virtus.pro.",
    updated: "2026-09-15",
    dpi: 400, sens: 2.2, edpi: 880, hz: 1000,
    resolution: "1280×960", aspect: "4:3 Stretched",
    mouse: "Zowie EC2-CW", mousepad: "Zowie G-SR",
    keyboard: "HyperX Alloy FPS", monitor: "Zowie XL2566K", headset: "HyperX Cloud II",
    crosshairCode: "CSGO-jE9Nv-aYMWG-yCuYW-DNTur-zYYwP",
    launchOptions: ["-novid", "-console"],
    viewmodel: "viewmodel_fov 68; viewmodel_offset_x 2.5; viewmodel_offset_y 0; viewmodel_offset_z -1.5; viewmodel_presetpos 1;",
    binds: [],
  },
  {
    id: "electroNic", nickname: "electroNic", realName: "Денис Шарипов", country: "🇷🇺",
    teamId: "vp", team: "Virtus.pro", role: "Rifler", verified: true,
    bio: "Опытный рифлер с отличным пониманием игры.",
    updated: "2026-09-15",
    dpi: 400, sens: 2.0, edpi: 800, hz: 1000,
    resolution: "1280×960", aspect: "4:3 Stretched",
    mouse: "Logitech G Pro X Superlight", mousepad: "Logitech G640",
    keyboard: "Logitech G Pro X", monitor: "Zowie XL2546K", headset: "HyperX Cloud II",
    crosshairCode: "CSGO-jE9Nv-aYMWG-yCuYW-DNTur-zYYwP",
    launchOptions: ["-novid", "-console", "-freq 360", "+fps_max 0"],
    viewmodel: "viewmodel_fov 68; viewmodel_offset_x 2.5; viewmodel_offset_y 0; viewmodel_offset_z -1.5; viewmodel_presetpos 1;",
    binds: [],
  },
  {
    id: "fl1t", nickname: "FL1T", realName: "Николай Лебедев", country: "🇷🇺",
    teamId: "vp", team: "Virtus.pro", role: "Rifler", verified: true,
    bio: "Молодой рифлер, восходящая звезда СНГ-сцены.",
    updated: "2026-09-15",
    dpi: 400, sens: 2.0, edpi: 800, hz: 1000,
    resolution: "1280×960", aspect: "4:3 Stretched",
    mouse: "Logitech G Pro X Superlight", mousepad: "Logitech G640",
    keyboard: "Logitech G Pro X", monitor: "Zowie XL2546K", headset: "HyperX Cloud II",
    crosshairCode: "—",
    launchOptions: ["-novid", "-console"],
    viewmodel: "viewmodel_fov 68; viewmodel_offset_x 2.5; viewmodel_offset_y 0; viewmodel_offset_z -1.5; viewmodel_presetpos 1;",
    binds: [],
  },

  // ============ FAZE ============
  {
    id: "karrigan", nickname: "karrigan", realName: "Финн Андерсен", country: "🇩🇰",
    teamId: "faze", team: "FaZe Clan", role: "IGL", verified: true,
    bio: "Легендарный IGL. Один из лучших капитанов в истории CS.",
    updated: "2026-09-15",
    dpi: 400, sens: 1.8, edpi: 720, hz: 1000,
    resolution: "1280×960", aspect: "4:3 Stretched",
    mouse: "Logitech G Pro X Superlight", mousepad: "Logitech G640",
    keyboard: "Logitech G Pro X", monitor: "Zowie XL2546K", headset: "Logitech G Pro X",
    crosshairCode: "—",
    launchOptions: ["-novid", "-console"],
    viewmodel: "viewmodel_fov 68; viewmodel_offset_x 2.5; viewmodel_offset_y 0; viewmodel_offset_z -1.5; viewmodel_presetpos 1;",
    binds: [],
  },
  {
    id: "ropz", nickname: "ropz", realName: "Робин Коль", country: "🇪🇪",
    teamId: "faze", team: "FaZe Clan", role: "Rifler", verified: true,
    bio: "Эстонский рифлер с математическим подходом к игре.",
    updated: "2026-09-15",
    dpi: 400, sens: 1.65, edpi: 660, hz: 4000,
    resolution: "1280×960", aspect: "4:3 Stretched",
    mouse: "Logitech G Pro X Superlight 2", mousepad: "Logitech G640",
    keyboard: "Logitech G Pro X", monitor: "Zowie XL2566K", headset: "Logitech G Pro X",
    crosshairCode: "—",
    launchOptions: ["-novid", "-console", "-freq 360"],
    viewmodel: "viewmodel_fov 68; viewmodel_offset_x 2.5; viewmodel_offset_y 0; viewmodel_offset_z -1.5; viewmodel_presetpos 1;",
    binds: [],
  },
  {
    id: "broky", nickname: "broky", realName: "Хельвийс Саукантс", country: "🇱🇻",
    teamId: "faze", team: "FaZe Clan", role: "AWPer", verified: true,
    bio: "Латвийский снайпер FaZe.",
    updated: "2026-09-15",
    dpi: 400, sens: 2.57, edpi: 1028, hz: 1000,
    resolution: "1280×960", aspect: "4:3 Stretched",
    mouse: "Logitech G Pro X Superlight", mousepad: "Logitech G640",
    keyboard: "Logitech G Pro X", monitor: "Zowie XL2566K", headset: "Logitech G Pro X",
    crosshairCode: "—",
    launchOptions: ["-novid", "-console"],
    viewmodel: "viewmodel_fov 68; viewmodel_offset_x 2.5; viewmodel_offset_y 0; viewmodel_offset_z -1.5; viewmodel_presetpos 1;",
    binds: [],
  },

  // ============ VITALITY ============
  {
    id: "zywoo", nickname: "ZywOo", realName: "Матьё Эрбо", country: "🇫🇷",
    teamId: "vitality", team: "Team Vitality", role: "AWPer", verified: true,
    bio: "Лучший игрок мира 2019, 2020, 2023. Универсал.",
    updated: "2026-09-15",
    dpi: 400, sens: 2.0, edpi: 800, hz: 1000,
    resolution: "1280×960", aspect: "4:3 Stretched",
    mouse: "Logitech G Pro X Superlight", mousepad: "Logitech G640",
    keyboard: "Logitech G Pro X", monitor: "Zowie XL2566K", headset: "Logitech G Pro X",
    crosshairCode: "—",
    launchOptions: ["-novid", "-console", "+fps_max 0"],
    viewmodel: "viewmodel_fov 68; viewmodel_offset_x 2.5; viewmodel_offset_y 0; viewmodel_offset_z -1.5; viewmodel_presetpos 1;",
    binds: [],
  },
  {
    id: "apex", nickname: "apEX", realName: "Дан Мейде", country: "🇫🇷",
    teamId: "vitality", team: "Team Vitality", role: "IGL", verified: true,
    bio: "Капитан Team Vitality. Эмоциональный лидер.",
    updated: "2026-09-15",
    dpi: 400, sens: 2.0, edpi: 800, hz: 1000,
    resolution: "1280×960", aspect: "4:3 Stretched",
    mouse: "Logitech G Pro X Superlight", mousepad: "Logitech G640",
    keyboard: "Logitech G Pro X", monitor: "Zowie XL2546K", headset: "Logitech G Pro X",
    crosshairCode: "—",
    launchOptions: ["-novid", "-console"],
    viewmodel: "viewmodel_fov 68; viewmodel_offset_x 2.5; viewmodel_offset_y 0; viewmodel_offset_z -1.5; viewmodel_presetpos 1;",
    binds: [],
  },

  // ============ MOUZ ============
  {
    id: "torzsi", nickname: "torzsi", realName: "Адам Тёрж", country: "🇭🇺",
    teamId: "mouz", team: "MOUZ", role: "AWPer", verified: true,
    bio: "Венгерский снайпер MOUZ.",
    updated: "2026-09-15",
    dpi: 400, sens: 1.5, edpi: 600, hz: 1000,
    resolution: "1280×960", aspect: "4:3 Stretched",
    mouse: "Logitech G Pro X Superlight", mousepad: "Logitech G640",
    keyboard: "Logitech G Pro X", monitor: "Zowie XL2566K", headset: "Logitech G Pro X",
    crosshairCode: "—",
    launchOptions: ["-novid", "-console"],
    viewmodel: "viewmodel_fov 68; viewmodel_offset_x 2.5; viewmodel_offset_y 0; viewmodel_offset_z -1.5; viewmodel_presetpos 1;",
    binds: [],
  },
  {
    id: "brollan", nickname: "Brollan", realName: "Людвиг Бролин", country: "🇸🇪",
    teamId: "mouz", team: "MOUZ", role: "Rifler", verified: true,
    bio: "Шведский рифлер MOUZ.",
    updated: "2026-09-15",
    dpi: 400, sens: 1.95, edpi: 780, hz: 1000,
    resolution: "1280×960", aspect: "4:3 Stretched",
    mouse: "Logitech G Pro X Superlight", mousepad: "Logitech G640",
    keyboard: "Logitech G Pro X", monitor: "Zowie XL2566K", headset: "Logitech G Pro X",
    crosshairCode: "CSGO-FnJLE-pUbZP-vnNr4-OEcBH-2zpxA",
    launchOptions: ["-novid", "-console"],
    viewmodel: "viewmodel_fov 68; viewmodel_offset_x 2.5; viewmodel_offset_y 0; viewmodel_offset_z -1.5; viewmodel_presetpos 1;",
    binds: [],
  },

  // ============ ASTRALIS ============
  {
    id: "dev1ce", nickname: "dev1ce", realName: "Николай Ридтц", country: "🇩🇰",
    teamId: "astralis", team: "Astralis", role: "AWPer", verified: true,
    bio: "Легендарный датский снайпер. Один из лучших в истории.",
    updated: "2026-09-15",
    dpi: 400, sens: 2.2, edpi: 880, hz: 1000,
    resolution: "1280×960", aspect: "4:3 Black Bars",
    mouse: "Logitech G Pro X Superlight", mousepad: "Logitech G640",
    keyboard: "Logitech G Pro X", monitor: "Zowie XL2566K", headset: "Logitech G Pro X",
    crosshairCode: "—",
    launchOptions: ["-novid", "-console"],
    viewmodel: "viewmodel_fov 68; viewmodel_offset_x 2.5; viewmodel_offset_y 0; viewmodel_offset_z -1.5; viewmodel_presetpos 1;",
    binds: [],
  },
  {
    id: "stavn", nickname: "stavn", realName: "Мартин Лунд", country: "🇩🇰",
    teamId: "astralis", team: "Astralis", role: "Rifler", verified: true,
    bio: "Датский рифлер Astralis.",
    updated: "2026-09-15",
    dpi: 800, sens: 1.8, edpi: 1440, hz: 1000,
    resolution: "1280×960", aspect: "4:3 Stretched",
    mouse: "Logitech G Pro X Superlight", mousepad: "Logitech G640",
    keyboard: "Logitech G Pro X", monitor: "Zowie XL2566K", headset: "Logitech G Pro X",
    crosshairCode: "—",
    launchOptions: ["-novid", "-console"],
    viewmodel: "viewmodel_fov 68; viewmodel_offset_x 2.5; viewmodel_offset_y 0; viewmodel_offset_z -1.5; viewmodel_presetpos 1;",
    binds: [],
  },
  {
    id: "jabbi", nickname: "jabbi", realName: "Якоб Нюгорд", country: "🇩🇰",
    teamId: "astralis", team: "Astralis", role: "Rifler", verified: true,
    bio: "Датский рифлер Astralis.",
    updated: "2026-09-15",
    dpi: 800, sens: 0.9, edpi: 720, hz: 1000,
    resolution: "1280×960", aspect: "4:3 Stretched",
    mouse: "Logitech G Pro X Superlight", mousepad: "Logitech G640",
    keyboard: "Logitech G Pro X", monitor: "Zowie XL2546K", headset: "Logitech G Pro X",
    crosshairCode: "CSGO-BsSeq-FHBbp-dmSed-msTmk-Ed7iL",
    launchOptions: ["-novid", "-console"],
    viewmodel: "viewmodel_fov 68; viewmodel_offset_x 2.5; viewmodel_offset_y 0; viewmodel_offset_z -1.5; viewmodel_presetpos 1;",
    binds: [],
  },

  // ============ LIQUID ============
  {
    id: "twistzz", nickname: "Twistzz", realName: "Рассел Ван Дулкен", country: "🇨🇦",
    teamId: "liquid", team: "Team Liquid", role: "Rifler", verified: true,
    bio: "Канадский рифлер с уникальной причёской.",
    updated: "2026-09-15",
    dpi: 400, sens: 1.55, edpi: 620, hz: 1000,
    resolution: "1280×960", aspect: "4:3 Stretched",
    mouse: "Logitech G Pro X Superlight 2", mousepad: "Logitech G640",
    keyboard: "Logitech G Pro X", monitor: "Zowie XL2566K", headset: "Logitech G Pro X",
    crosshairCode: "—",
    launchOptions: ["-novid", "-console"],
    viewmodel: "viewmodel_fov 68; viewmodel_offset_x 2.5; viewmodel_offset_y 0; viewmodel_offset_z -1.5; viewmodel_presetpos 1;",
    binds: [],
  },
  {
    id: "elige", nickname: "EliGE", realName: "Джонатан Яблоновски", country: "🇺🇸",
    teamId: "liquid", team: "Team Liquid", role: "Rifler", verified: true,
    bio: "Американский рифлер, ветеран сцены.",
    updated: "2026-09-15",
    dpi: 1600, sens: 0.65, edpi: 1040, hz: 1000,
    resolution: "1680×1050", aspect: "16:10 Stretched",
    mouse: "Logitech G Pro X Superlight 2", mousepad: "Logitech G640",
    keyboard: "Logitech G Pro X", monitor: "Zowie XL2566K", headset: "Logitech G Pro X",
    crosshairCode: "—",
    launchOptions: ["-novid", "-console"],
    viewmodel: "viewmodel_fov 68; viewmodel_offset_x 2.5; viewmodel_offset_y 0; viewmodel_offset_z -1.5; viewmodel_presetpos 1;",
    binds: [],
  },

  // ============ HEROIC ============
  {
    id: "nilo", nickname: "nilo", realName: "—", country: "🇸🇪",
    teamId: "heroic", team: "HEROIC", role: "Rifler", verified: true,
    bio: "Шведский рифлер HEROIC.",
    updated: "2026-09-15",
    dpi: 800, sens: 0.9, edpi: 720, hz: 1000,
    resolution: "1280×960", aspect: "4:3 Stretched",
    mouse: "Logitech G Pro X Superlight", mousepad: "Logitech G640",
    keyboard: "Logitech G Pro X", monitor: "Zowie XL2546K", headset: "Logitech G Pro X",
    crosshairCode: "CSGO-qqtZn-tX4V5-NU7Gm-rkCTG-CuSyL",
    launchOptions: ["-novid", "-console", "-freq 240", "-tickrate 128"],
    viewmodel: "viewmodel_fov 68; viewmodel_offset_x 2.5; viewmodel_offset_y 0; viewmodel_offset_z -1.5; viewmodel_presetpos 1;",
    binds: [],
  },

  // ============ CLOUD9 ============
  {
    id: "interz", nickname: "interz", realName: "Тимур Ерофеев", country: "🇷🇺",
    teamId: "c9", team: "Cloud9", role: "Support", verified: true,
    bio: "Русский саппорт Cloud9.",
    updated: "2026-09-15",
    dpi: 400, sens: 1.9, edpi: 760, hz: 1000,
    resolution: "1280×960", aspect: "4:3 Stretched",
    mouse: "Logitech G Pro X Superlight", mousepad: "Logitech G640",
    keyboard: "Logitech G Pro X", monitor: "Zowie XL2546K", headset: "HyperX Cloud II",
    crosshairCode: "—",
    launchOptions: ["-novid", "-console"],
    viewmodel: "viewmodel_fov 68; viewmodel_offset_x 2.5; viewmodel_offset_y 0; viewmodel_offset_z -1.5; viewmodel_presetpos 1;",
    binds: [],
  },
  {
    id: "ax1le", nickname: "Ax1Le", realName: "Сергей Рыхторов", country: "🇷🇺",
    teamId: "c9", team: "Cloud9", role: "Rifler", verified: true,
    bio: "Русский рифлер Cloud9.",
    updated: "2026-09-15",
    dpi: 400, sens: 1.7, edpi: 680, hz: 1000,
    resolution: "1280×960", aspect: "4:3 Stretched",
    mouse: "Logitech G Pro X Superlight", mousepad: "Logitech G640",
    keyboard: "Logitech G Pro X", monitor: "Zowie XL2566K", headset: "HyperX Cloud II",
    crosshairCode: "—",
    launchOptions: ["-novid", "-console"],
    viewmodel: "viewmodel_fov 68; viewmodel_offset_x 2.5; viewmodel_offset_y 0; viewmodel_offset_z -1.5; viewmodel_presetpos 1;",
    binds: [],
  },

  // ============ WW TEAM (стримеры) ============
  {
    id: "deko", nickname: "deko", realName: "Денис Жуков", country: "🇷🇺",
    teamId: "ww", team: "WW Team", role: "Стример", verified: true,
    bio: "Экс-профессиональный снайпер, теперь популярный стример CS2. Бывший игрок Quantum Bellator Fire, EXTREMUM, 1win Team и Aurora.",
    twitch: "https://www.twitch.tv/deko",
    updated: "2026-09-15",
    dpi: 400, sens: 2.7, edpi: 1080, hz: 1000,
    resolution: "1600×1024", aspect: "16:10 Stretched",
    mouse: "Logitech G Pro X Superlight 2", mousepad: "Logitech G640",
    keyboard: "Logitech G Pro X TKL", monitor: "Zowie XL2566K", headset: "HyperX Cloud II",
    crosshairCode: "CSGO-JA7fJ-8vd9D-Z4A9Y-bO6tt-OYBpF",
    launchOptions: [],
    viewmodel: "viewmodel_fov 68; viewmodel_offset_x 2.5; viewmodel_offset_y 0; viewmodel_offset_z -1.5; viewmodel_presetpos 1;",
    binds: [],
  },
  {
    id: "m3wsu", nickname: "m3wsu", realName: "Тимур Коренев", country: "🇷🇺",
    teamId: "ww", team: "WW Team", role: "Стример", verified: true,
    bio: "Русскоязычный Twitch-стример CS2, профессиональный игрок WW Team. Более 259 000 подписчиков.",
    twitch: "https://www.twitch.tv/m3wsu",
    updated: "2026-09-15",
    dpi: 400, sens: 1.7, edpi: 680, hz: 1000,
    resolution: "1280×960", aspect: "4:3 Stretched",
    mouse: "Logitech G Pro X Superlight 2", mousepad: "Logitech G640",
    keyboard: "Logitech G Pro X TKL", monitor: "Zowie XL2566K", headset: "HyperX Cloud II",
    crosshairCode: "CSGO-p2zoS-UPbBL-HiKjK-46ufH-5tbJD",
    launchOptions: ["-freq 360", "-allow_third_party_software", "+fps_max 999", "+rate 1000000"],
    viewmodel: "viewmodel_fov 68; viewmodel_offset_x 2.5; viewmodel_offset_y 0; viewmodel_offset_z -1.5; viewmodel_presetpos 2;",
    binds: [],
  },
  {
    id: "ct0m", nickname: "ct0m", realName: "Артём Максимов", country: "🇷🇺",
    teamId: "ww", team: "WW Team", role: "Стример", verified: true,
    bio: "Русский стример CS2, игрок WW Team. Стал известен после выступлений в mix POLET.",
    twitch: "https://www.twitch.tv/ct0m",
    updated: "2026-09-15",
    dpi: 400, sens: 0.9, edpi: 360, hz: 1000,
    resolution: "1280×1024", aspect: "4:3 Stretched",
    mouse: "Logitech G Pro X Superlight", mousepad: "Logitech G640",
    keyboard: "Logitech G Pro X", monitor: "Zowie XL2566K", headset: "HyperX Cloud II",
    crosshairCode: "CSGO-WktFi-v7edr-Dc42P-MiOdp-VYq3B",
    launchOptions: [],
    viewmodel: "viewmodel_fov 68; viewmodel_offset_x 2.5; viewmodel_offset_y 0; viewmodel_offset_z -1.5; viewmodel_presetpos 1;",
    binds: [],
  },

  // ============ СТРИМЕРЫ (без команды) ============
  {
    id: "shadowkekw", nickname: "shadowkekw", realName: "Максим Павлов", country: "🇷🇺",
    teamId: "streamer", team: "Стример", role: "Стример", verified: true,
    bio: "Один из самых популярных русскоязычных стримеров CS2. Более 1 млн подписчиков на Twitch.",
    twitch: "https://www.twitch.tv/shadowkekw",
    updated: "2026-09-15",
    dpi: 800, sens: 1.9, edpi: 1520, hz: 1000,
    resolution: "1280×1024", aspect: "4:3 Stretched",
    mouse: "Logitech G Pro X Superlight", mousepad: "Logitech G640",
    keyboard: "Logitech G Pro X", monitor: "Zowie XL2546K", headset: "HyperX Cloud II",
    crosshairCode: "CSGO-KTaY3-rXci2-9DTXB-aPuKV-MDr7C",
    launchOptions: [],
    viewmodel: "viewmodel_fov 68; viewmodel_offset_x 2.5; viewmodel_offset_y 0; viewmodel_offset_z -1.5; viewmodel_presetpos 2;",
    binds: [],
  },
  {
    id: "strogo", nickname: "StRoGo", realName: "Иван Шурпатов", country: "🇷🇺",
    teamId: "streamer", team: "Стример", role: "Стример", verified: true,
    bio: "Победитель премии SLAY 2025 в номинации «Лучший стример CS2». Игрок WW Team.",
    twitch: "https://www.twitch.tv/strogo",
    updated: "2026-09-15",
    dpi: 600, sens: 0.85, edpi: 510, hz: 1000,
    resolution: "1440×1080", aspect: "4:3 Stretched",
    mouse: "Logitech G Pro X Superlight", mousepad: "Logitech G640",
    keyboard: "Logitech G Pro X", monitor: "Zowie XL2566K", headset: "HyperX Cloud II",
    crosshairCode: "CSGO-NmcdV-ORLFj-vKC4W-LV6zW-4fWjM",
    launchOptions: [],
    viewmodel: "viewmodel_fov 68; viewmodel_offset_x 2.5; viewmodel_offset_y 2; viewmodel_offset_z -2; viewmodel_presetpos 2;",
    binds: [],
  },
  {
    id: "bratishkin", nickname: "Bratishkinoff", realName: "Владимир Семенюк", country: "🇷🇺",
    teamId: "streamer", team: "Стример", role: "Стример", verified: true,
    bio: "Российский стример, один из самых популярных контент-мейкеров СНГ. 3,7 млн подписчиков на Twitch.",
    twitch: "https://www.twitch.tv/bratishkinoff",
    updated: "2026-09-15",
    dpi: 500, sens: 1.25, edpi: 625, hz: 1000,
    resolution: "1920×1080", aspect: "16:9 Native",
    mouse: "Logitech G Pro X Superlight", mousepad: "Logitech G640",
    keyboard: "Logitech G Pro X", monitor: "Zowie XL2546K", headset: "HyperX Cloud II",
    crosshairCode: "CSGO-Wjfc4-QPKRt-XdZBP-Tmebr-3WDND",
    launchOptions: [],
    viewmodel: "viewmodel_fov 68; viewmodel_offset_x 1; viewmodel_offset_y 1; viewmodel_offset_z -2; viewmodel_presetpos 1;",
    binds: [],
  },
  {
    id: "buster", nickname: "Buster", realName: "Вячеслав Леонтьев", country: "🇷🇺",
    teamId: "streamer", team: "Стример", role: "Стример", verified: true,
    bio: "Экс-профессиональный игрок, теперь популярный стример CS2. 8,4 млн часов просмотра за 2024 год.",
    twitch: "https://www.twitch.tv/buster",
    updated: "2026-09-15",
    dpi: 400, sens: 2.2, edpi: 880, hz: 1000,
    resolution: "1280×960", aspect: "4:3 Stretched",
    mouse: "Zowie EC2", mousepad: "Logitech G640",
    keyboard: "Logitech G Pro X", monitor: "Zowie XL2546", headset: "HyperX Cloud II",
    crosshairCode: "CSGO-y6a6Y-89Jt8-J5WSy-zC5BJ-OjPJM",
    launchOptions: [],
    viewmodel: "viewmodel_fov 68; viewmodel_offset_x 2.5; viewmodel_offset_y 0; viewmodel_offset_z -1.5; viewmodel_presetpos 1;",
    binds: [],
  },
  {
    id: "evelone", nickname: "Evelone", realName: "Вадим Казаков", country: "🇷🇺",
    teamId: "streamer", team: "Стример", role: "Стример", verified: true,
    bio: "Популярный русскоязычный стример, 484 000 пиковых зрителей. 7,9 млн часов просмотра за 2024 год.",
    twitch: "https://www.twitch.tv/evelone2004",
    updated: "2026-09-15",
    dpi: 400, sens: 1.8, edpi: 720, hz: 1000,
    resolution: "1280×960", aspect: "4:3 Stretched",
    mouse: "Logitech G Pro X Superlight", mousepad: "Logitech G640",
    keyboard: "Logitech G Pro X", monitor: "Zowie XL2546K", headset: "HyperX Cloud II",
    crosshairCode: "CSGO-VLwPT-PM4Ue-FyPFv-Nwta9-tvwPB",
    launchOptions: [],
    viewmodel: "viewmodel_fov 68; viewmodel_offset_x 2.5; viewmodel_offset_y 0; viewmodel_offset_z -1.5; viewmodel_presetpos 1;",
    binds: [],
  },
  {
    id: "skywhywalker", nickname: "skywhywalker", realName: "Тимур Леонов", country: "🇷🇺",
    teamId: "streamer", team: "Стример", role: "Стример", verified: true,
    bio: "Популярный русскоязычный стример CS2.",
    twitch: "https://www.twitch.tv/skywhywalker",
    updated: "2026-09-15",
    dpi: 1600, sens: 1.25, edpi: 2000, hz: 1000,
    resolution: "1440×1080", aspect: "4:3 Stretched",
    mouse: "Ninjutso Sora V2", mousepad: "Artisan FX 99 Type",
    keyboard: "Wooting 80HE Ghost", monitor: "SDC 27X1QE", headset: "MoonDrop Blessing 3",
    crosshairCode: "CSGO-WktFi-v7edr-Dc42P-MiOdp-VYq3B",
    launchOptions: ["-fps_max 0", "-allow_third_party_software"],
    viewmodel: "viewmodel_fov 68; viewmodel_offset_x 2.5; viewmodel_offset_y 2; viewmodel_offset_z -2; viewmodel_presetpos 0;",
    binds: [],
  },
  {
    id: "kiryuha", nickname: "KiryuhaNastyuha", realName: "Кирилл Михайлов", country: "🇷🇺",
    teamId: "streamer", team: "Стример", role: "Стример", verified: true,
    bio: "Русскоязычный стример CS2.",
    twitch: "https://www.twitch.tv/kiryuha_nastyuha",
    updated: "2026-09-15",
    dpi: 800, sens: 1.1, edpi: 880, hz: 1000,
    resolution: "1280×960", aspect: "4:3 Stretched",
    mouse: "Logitech G Pro X Superlight", mousepad: "Logitech G640",
    keyboard: "Logitech G Pro X", monitor: "Zowie XL2546K", headset: "HyperX Cloud II",
    crosshairCode: "CSGO-bAFK4-WaJwX-4OedX-qOh4S-MDr7C",
    launchOptions: [],
    viewmodel: "viewmodel_fov 68; viewmodel_offset_x 2.5; viewmodel_offset_y 0; viewmodel_offset_z -1.5; viewmodel_presetpos 1;",
    binds: [],
  },
  {
    id: "formixyouknow", nickname: "formixyouknow", realName: "Виталий Тюрин", country: "🇷🇺",
    teamId: "streamer", team: "Стример", role: "Стример", verified: true,
    bio: "Русскоязычный стример CS2 на Twitch и Kick.",
    twitch: "https://www.twitch.tv/formixyouknow",
    updated: "2026-09-15",
    dpi: 800, sens: 1.26, edpi: 1008, hz: 1000,
    resolution: "1280×960", aspect: "4:3 Stretched",
    mouse: "Logitech G Pro X Superlight", mousepad: "Logitech G640",
    keyboard: "Logitech G Pro X", monitor: "Zowie XL2546K", headset: "HyperX Cloud II",
    crosshairCode: "CSGO-mSWN5-W8T6T-dM42F-v8YdA-tLNMB",
    launchOptions: [],
    viewmodel: "viewmodel_fov 68; viewmodel_offset_x 2.5; viewmodel_offset_y 0; viewmodel_offset_z -1.5; viewmodel_presetpos 1;",
    binds: [],
  },
  {
    id: "yurapivo", nickname: "yurapivo", realName: "Юрий Лаптев", country: "🇷🇺",
    teamId: "streamer", team: "Стример", role: "Стример", verified: true,
    bio: "Русскоязычный стример CS2.",
    twitch: "https://www.twitch.tv/yurapivo",
    updated: "2026-09-15",
    dpi: 1000, sens: 0.77, edpi: 770, hz: 1000,
    resolution: "1920×1080", aspect: "16:9 Native",
    mouse: "Logitech G Pro X Superlight", mousepad: "Logitech G640",
    keyboard: "Logitech G Pro X", monitor: "Zowie XL2546K", headset: "HyperX Cloud II",
    crosshairCode: "CSGO-2LsWa-kOaQe-4zscr-h7ovB-BjTiA",
    launchOptions: [],
    viewmodel: "viewmodel_fov 68; viewmodel_offset_x 2.5; viewmodel_offset_y 0; viewmodel_offset_z -1.5; viewmodel_presetpos 1;",
    binds: [],
  },
  {
    id: "klyanus", nickname: "KLYANUS", realName: "—", country: "🇷🇺",
    teamId: "streamer", team: "Стример", role: "Стример", verified: true,
    bio: "Русскоязычный стример CS2.",
    twitch: "https://www.twitch.tv/klyanus",
    updated: "2026-09-15",
    dpi: 400, sens: 1.79, edpi: 716, hz: 1000,
    resolution: "1280×1024", aspect: "4:3 Stretched",
    mouse: "Logitech G Pro X Superlight", mousepad: "Logitech G640",
    keyboard: "Logitech G Pro X", monitor: "Zowie XL2546K", headset: "HyperX Cloud II",
    crosshairCode: "CSGO-CCzED-2kmMo-jdq6t-UG3MP-LkYbD",
    launchOptions: [],
    viewmodel: "viewmodel_fov 68; viewmodel_offset_x 2.5; viewmodel_offset_y 0; viewmodel_offset_z -1.5; viewmodel_presetpos 1;",
    binds: [],
  },
  {
    id: "pava", nickname: "pava", realName: "—", country: "🇷🇺",
    teamId: "streamer", team: "Стример", role: "Стример", verified: true,
    bio: "Русскоязычный стример CS2.",
    twitch: "https://www.twitch.tv/pava",
    updated: "2026-09-15",
    dpi: 800, sens: 0.97, edpi: 776, hz: 1000,
    resolution: "1920×1080", aspect: "16:9 Native",
    mouse: "Logitech G Pro X Superlight", mousepad: "Logitech G640",
    keyboard: "Logitech G Pro X", monitor: "Zowie XL2546K", headset: "HyperX Cloud II",
    crosshairCode: "CSGO-UDPrn-WwVU7-Pf7kP-bY9DK-8SfOQ",
    launchOptions: [],
    viewmodel: "viewmodel_fov 68; viewmodel_offset_x 2.5; viewmodel_offset_y 0; viewmodel_offset_z -1.5; viewmodel_presetpos 1;",
    binds: [],
  },
  {
    id: "unoniceguy", nickname: "unoniceguy", realName: "—", country: "🇷🇺",
    teamId: "streamer", team: "Стример", role: "Стример", verified: true,
    bio: "Русскоязычный стример CS2.",
    twitch: "https://www.twitch.tv/unoniceguy",
    updated: "2026-09-15",
    dpi: 1000, sens: 1.0, edpi: 1000, hz: 2000,
    resolution: "1280×960", aspect: "4:3 Stretched",
    mouse: "Logitech G Pro X Superlight", mousepad: "Logitech G640",
    keyboard: "Logitech G Pro X", monitor: "Zowie XL2546K", headset: "HyperX Cloud II",
    crosshairCode: "—",
    launchOptions: [],
    viewmodel: "viewmodel_fov 68; viewmodel_offset_x 2.5; viewmodel_offset_y 0; viewmodel_offset_z -1.5; viewmodel_presetpos 1;",
    binds: [],
  },
  {
    id: "ubica", nickname: "Ubica", realName: "Александр Иванов", country: "🇷🇺",
    teamId: "streamer", team: "Стример", role: "Стример", verified: true,
    bio: "Русскоязычный стример CS2.",
    twitch: "https://www.twitch.tv/ubica",
    updated: "2026-09-15",
    dpi: 800, sens: 1.5, edpi: 1200, hz: 1000,
    resolution: "1280×960", aspect: "4:3 Stretched",
    mouse: "Logitech G Pro X Superlight", mousepad: "Logitech G640",
    keyboard: "Logitech G Pro X", monitor: "Zowie XL2546K", headset: "HyperX Cloud II",
    crosshairCode: "CSGO-8kqGP-4ApJh-tJBY7-UYhjQ-F99zP",
    launchOptions: [],
    viewmodel: "viewmodel_fov 68; viewmodel_offset_x 2.5; viewmodel_offset_y 0; viewmodel_offset_z -1.5; viewmodel_presetpos 1;",
    binds: [],
  },
];

export const getPlayer = (id: string) => players.find((p) => p.id === id);
export const getPlayersByTeam = (teamId: string) => players.filter((p) => p.teamId === teamId);